namespace: ansible
name: unix
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies:
  ansible.misc: '>=1.0'
  ansible.windows: '>=1.0'
  ansible.infoblox: '>=1.0'
repository: git@github.com:coll-test/ansible.unix.git
documentation: https://github.com/coll-test/ansible.unix/tree/master/docs
homepage: https://github.com/coll-test/ansible.unix
issues: https://github.com/coll-test/ansible.unix/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
